/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: sfuentez (https://sketchfab.com/sfuentez)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/golden-music-de3145138e724a31a9d19ae7f578f968
title: GOLDEN MUSIC
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Music({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/music.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={500}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1205.71, 82.27, -169.02]}>
            <group position={[-4.56, 5.27, -245.22]} rotation={[-Math.PI, 0, Math.PI]}>
              <group position={[395.5, 15.61, 25.84]} rotation={[0.18, 0.06, -1.72]}>
                <group position={[0.28, 1.18, -1.56]}>
                  <group position={[0.93, 5.97, -1.08]}>
                    <mesh geometry={nodes.DONA_Mat_0.geometry} material={nodes.DONA_Mat_0.material} />
                  </group>
                  <group position={[0.93, 5.97, -1.08]}>
                    <mesh geometry={nodes.CHOC_Mat_3001_0.geometry} material={nodes.CHOC_Mat_3001_0.material} />
                  </group>
                </group>
                <group position={[1.55, 3.28, -6.47]}>
                  <mesh geometry={nodes.Tubo_1_Mat_3001_0.geometry} material={nodes.Tubo_1_Mat_3001_0.material} />
                </group>
              </group>
              <group position={[-395.38, 8.01, 20.7]}>
                <group position={[-7.77, 5.46, -6.86]} rotation={[-0.18, -0.06, 1.69]}>
                  <mesh geometry={nodes.Tubo_Mat_3001_0.geometry} material={nodes.Tubo_Mat_3001_0.material} />
                </group>
                <group position={[1.02, -0.16, -1.69]} rotation={[-0.18, -0.06, 1.69]}>
                  <group position={[1, 5.98, -1.08]}>
                    <mesh geometry={nodes.DONA_2_Mat_0.geometry} material={nodes.DONA_2_Mat_0.material} />
                  </group>
                  <group position={[1, 5.98, -1.08]}>
                    <mesh geometry={nodes.CHOC_2_Mat_3001_0.geometry} material={nodes.CHOC_2_Mat_3001_0.material} />
                  </group>
                </group>
              </group>
              <group position={[-0.12, -23.63, -46.54]} rotation={[-Math.PI, 0, Math.PI]}>
                <group position={[1366.94, -96.64, 127.73]}>
                  <group position={[-1363.58, 401.76, -198.04]}>
                    <group position={[0, 282.06, 0]}>
                      <mesh
                        geometry={nodes.Band_cushon_Mat002_0.geometry}
                        material={nodes.Band_cushon_Mat002_0.material}
                      />
                    </group>
                    <group position={[0, 282.06, 0]}>
                      <mesh geometry={nodes.Top_band_Mat_3002_0.geometry} material={materials['Mat_3.002']} />
                    </group>
                  </group>
                  <group position={[-1363.58, -401.76, 198.04]}>
                    <group position={[0, 803.52, -396.09]}>
                      <group position={[446.92, 21.6, 0]}>
                        <mesh
                          geometry={nodes.Polygon_2_Mat_3001_0.geometry}
                          material={nodes.Polygon_2_Mat_3001_0.material}
                        />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
            <group position={[1.78, -82.27, 169.02]}>
              <mesh geometry={nodes.Big_Size_Mat1_0.geometry} material={nodes.Big_Size_Mat1_0.material} />
            </group>
            <group position={[2.78, 77, 76.2]} rotation={[-0.07, 0, 0]}>
              <group position={[169.62, -6.65, -14.98]} rotation={[1.64, -0.01, -0.17]}>
                <group position={[0, 0, 0.74]}>
                  <mesh geometry={nodes.DONA_3_Mat_0.geometry} material={nodes.DONA_3_Mat_0.material} />
                  <mesh geometry={nodes.CHOC_3_Mat1_0.geometry} material={nodes.CHOC_3_Mat1_0.material} />
                </group>
                <group position={[0, 0, -1.48]}>
                  <group position={[-27.1, 32.72, -54.46]} rotation={[2.05, -0.13, 2.21]} scale={[0.48, 0.48, 0.48]}>
                    <mesh
                      geometry={nodes.Cilindro_1_0_Mat001_0.geometry}
                      material={nodes.Cilindro_1_0_Mat001_0.material}
                    />
                  </group>
                  <group position={[72.59, 45.34, -48.82]} rotation={[1.8, 0.05, 0.56]} scale={[0.7, 0.7, 0.7]}>
                    <mesh geometry={nodes.Cilindro_1_Mat002_0.geometry} material={nodes.Cilindro_1_Mat002_0.material} />
                  </group>
                  <group position={[105.41, 43.86, 23.45]} rotation={[1.73, 0.07, -0.38]} scale={[0.77, 0.77, 0.77]}>
                    <mesh
                      geometry={nodes.Cilindro_1_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[25.98, 33.35, -119.52]} rotation={[0.92, 0.21, -0.78]} scale={[1.21, 1.21, 1.21]}>
                    <mesh geometry={nodes.Cilindro_3_Mat002_0.geometry} material={nodes.Cilindro_3_Mat002_0.material} />
                  </group>
                  <group position={[28.3, 42.61, -70.6]} rotation={[1.96, 0.45, -0.64]} scale={[0.64, 0.64, 0.64]}>
                    <mesh
                      geometry={nodes.Cilindro_1_4_Mat001_0.geometry}
                      material={nodes.Cilindro_1_4_Mat001_0.material}
                    />
                  </group>
                  <group position={[-69.64, 45.55, 60.52]} rotation={[1.92, 0.03, -1.29]} scale={[0.68, 0.68, 0.68]}>
                    <mesh geometry={nodes.Cilindro_5_Mat002_0.geometry} material={nodes.Cilindro_5_Mat002_0.material} />
                  </group>
                  <group position={[-47.09, 44.07, -93.62]} rotation={[1.4, -0.22, 2.78]} scale={[0.82, 0.82, 0.82]}>
                    <mesh
                      geometry={nodes.Cilindro_1_6_Mat001_0.geometry}
                      material={nodes.Cilindro_1_6_Mat001_0.material}
                    />
                  </group>
                  <group position={[-47.09, 39.29, -105.47]} rotation={[0.62, 0.05, -0.13]} scale={[0.94, 0.94, 0.94]}>
                    <mesh geometry={nodes.Cilindro_7_Mat002_0.geometry} material={nodes.Cilindro_7_Mat002_0.material} />
                  </group>
                  <group position={[81.5, 45.4, -34.26]} rotation={[1.29, -0.07, 1.57]} scale={[0.63, 0.63, 0.63]}>
                    <mesh
                      geometry={nodes.Cilindro_1_8_Mat001_0.geometry}
                      material={nodes.Cilindro_1_8_Mat001_0.material}
                    />
                  </group>
                  <group position={[-76.32, 21.93, 111.54]} rotation={[2.69, 0.47, -2.51]} scale={[2, 2, 2]}>
                    <mesh geometry={nodes.Cilindro_9_Mat002_0.geometry} material={nodes.Cilindro_9_Mat002_0.material} />
                  </group>
                  <group position={[35.43, 45.59, -81.89]} rotation={[1.37, -0.11, 1.29]} scale={[0.68, 0.68, 0.68]}>
                    <mesh
                      geometry={nodes.Cilindro_1_10_Mat001_0.geometry}
                      material={nodes.Cilindro_1_10_Mat001_0.material}
                    />
                  </group>
                  <group position={[42.64, 44.84, 76.59]} rotation={[1.2, 0.39, -2.65]} scale={[0.73, 0.73, 0.73]}>
                    <mesh
                      geometry={nodes.Cilindro_11_Mat002_0.geometry}
                      material={nodes.Cilindro_11_Mat002_0.material}
                    />
                  </group>
                  <group position={[24.9, 33.88, 125.24]} rotation={[2.13, -0.12, 2.97]} scale={[1.09, 1.09, 1.09]}>
                    <mesh
                      geometry={nodes.Cilindro_1_12_Mat001_0.geometry}
                      material={nodes.Cilindro_1_12_Mat001_0.material}
                    />
                  </group>
                  <group position={[-85.36, 45.7, 46.55]} rotation={[1.55, -0.31, 1.61]} scale={[0.87, 0.87, 0.87]}>
                    <mesh
                      geometry={nodes.Cilindro_1_100_Mat001_0.geometry}
                      material={nodes.Cilindro_1_100_Mat001_0.material}
                    />
                  </group>
                  <group position={[61.92, 17.98, 125.09]} rotation={[2.48, -0.73, 0.46]} scale={[1.47, 1.47, 1.47]}>
                    <mesh
                      geometry={nodes.Cilindro_101_Mat002_0.geometry}
                      material={nodes.Cilindro_101_Mat002_0.material}
                    />
                  </group>
                  <group position={[-65.66, 43.62, -45.23]} rotation={[1.48, -0.06, -0.9]} scale={[0.7, 0.7, 0.7]}>
                    <mesh
                      geometry={nodes.Cilindro_1_102_Mat001_0.geometry}
                      material={nodes.Cilindro_1_102_Mat001_0.material}
                    />
                  </group>
                  <group position={[-89.95, 42.96, -61.54]} rotation={[1.23, -0.06, 1.1]} scale={[0.85, 0.85, 0.85]}>
                    <mesh
                      geometry={nodes.Cilindro_103_Mat002_0.geometry}
                      material={nodes.Cilindro_103_Mat002_0.material}
                    />
                  </group>
                  <group position={[-49.09, 11.27, 23.7]} rotation={[-1.3, -0.1, -1.82]} scale={[0.15, 0.15, 0.15]}>
                    <mesh
                      geometry={nodes.Cilindro_1_104_Mat001_0.geometry}
                      material={nodes.Cilindro_1_104_Mat001_0.material}
                    />
                  </group>
                  <group position={[-54.64, 38.1, -40.67]} rotation={[1.93, -0.15, -1.45]} scale={[0.56, 0.56, 0.56]}>
                    <mesh
                      geometry={nodes.Cilindro_105_Mat002_0.geometry}
                      material={nodes.Cilindro_105_Mat002_0.material}
                    />
                  </group>
                  <group position={[127.41, 29.94, -21.13]} rotation={[1.39, -0.68, -2.53]} scale={[1.06, 1.06, 1.06]}>
                    <mesh
                      geometry={nodes.Cilindro_1_106_Mat001_0.geometry}
                      material={nodes.Cilindro_1_106_Mat001_0.material}
                    />
                  </group>
                  <group position={[7.29, 42.69, -75.77]} rotation={[1.69, -0.07, -1.55]} scale={[0.69, 0.69, 0.69]}>
                    <mesh
                      geometry={nodes.Cilindro_107_Mat002_0.geometry}
                      material={nodes.Cilindro_107_Mat002_0.material}
                    />
                  </group>
                  <group position={[-89.84, 45.23, 48.96]} rotation={[1.9, 0.38, 2.71]} scale={[0.75, 0.75, 0.75]}>
                    <mesh
                      geometry={nodes.Cilindro_1_108_Mat001_0.geometry}
                      material={nodes.Cilindro_1_108_Mat001_0.material}
                    />
                  </group>
                  <group position={[15.94, 42.15, -108.87]} rotation={[0.84, -0.35, 0.73]} scale={[0.94, 0.94, 0.94]}>
                    <mesh
                      geometry={nodes.Cilindro_109_Mat002_0.geometry}
                      material={nodes.Cilindro_109_Mat002_0.material}
                    />
                  </group>
                  <group position={[34.62, 43.88, -71.95]} rotation={[1.63, -0.29, 0.68]} scale={[0.6, 0.6, 0.6]}>
                    <mesh
                      geometry={nodes.Cilindro_1_110_Mat001_0.geometry}
                      material={nodes.Cilindro_1_110_Mat001_0.material}
                    />
                  </group>
                  <group position={[-63.12, 45.56, 77.79]} rotation={[1.74, -0.19, 1.65]} scale={[0.78, 0.78, 0.78]}>
                    <mesh
                      geometry={nodes.Cilindro_111_Mat002_0.geometry}
                      material={nodes.Cilindro_111_Mat002_0.material}
                    />
                  </group>
                  <group position={[-40.26, 11.77, 132.96]} rotation={[-2.3, -0.04, 0.75]} scale={[0.37, 0.37, 0.37]}>
                    <mesh
                      geometry={nodes.Cilindro_1_112_Mat001_0.geometry}
                      material={nodes.Cilindro_1_112_Mat001_0.material}
                    />
                  </group>
                  <group position={[-61.6, 41.96, -43.25]} rotation={[2.07, -0.09, 2.56]} scale={[0.6, 0.6, 0.6]}>
                    <mesh
                      geometry={nodes.Cilindro_113_Mat002_0.geometry}
                      material={nodes.Cilindro_113_Mat002_0.material}
                    />
                  </group>
                  <group position={[87.7, 45.18, 53.57]} rotation={[2.05, -0.26, 2.62]} scale={[0.84, 0.84, 0.84]}>
                    <mesh
                      geometry={nodes.Cilindro_1_114_Mat001_0.geometry}
                      material={nodes.Cilindro_1_114_Mat001_0.material}
                    />
                  </group>
                  <group position={[136.04, 19.5, 7.42]} rotation={[-0.24, -1.34, -1.34]} scale={[0.88, 0.88, 0.88]}>
                    <mesh
                      geometry={nodes.Cilindro_115_Mat002_0.geometry}
                      material={nodes.Cilindro_115_Mat002_0.material}
                    />
                  </group>
                  <group position={[7.7, 29.38, -57.01]} rotation={[2.33, -0.21, 1.03]} scale={[0.43, 0.43, 0.43]}>
                    <mesh
                      geometry={nodes.Cilindro_1_116_Mat001_0.geometry}
                      material={nodes.Cilindro_1_116_Mat001_0.material}
                    />
                  </group>
                  <group position={[112.85, 24.39, 78.91]} rotation={[1.81, -0.74, -0.2]} scale={[1.19, 1.19, 1.19]}>
                    <mesh
                      geometry={nodes.Cilindro_117_Mat002_0.geometry}
                      material={nodes.Cilindro_117_Mat002_0.material}
                    />
                  </group>
                  <group position={[73.81, 45.15, 72.37]} rotation={[1.66, -0.53, 0.38]} scale={[0.96, 0.96, 0.96]}>
                    <mesh
                      geometry={nodes.Cilindro_1_118_Mat001_0.geometry}
                      material={nodes.Cilindro_1_118_Mat001_0.material}
                    />
                  </group>
                  <group position={[116.47, 9.69, -72.21]} rotation={[0.27, -1.25, 0.67]} scale={[0.96, 0.96, 0.96]}>
                    <mesh
                      geometry={nodes.Cilindro_119_Mat002_0.geometry}
                      material={nodes.Cilindro_119_Mat002_0.material}
                    />
                  </group>
                  <group position={[100, 9.17, -88.8]} rotation={[-1.7, -0.14, -0.96]} scale={[0.38, 0.38, 0.38]}>
                    <mesh
                      geometry={nodes.Cilindro_1_120_Mat001_0.geometry}
                      material={nodes.Cilindro_1_120_Mat001_0.material}
                    />
                  </group>
                  <group position={[-53.84, 42.53, -54.14]} rotation={[1.89, 0.16, -1.73]} scale={[0.61, 0.61, 0.61]}>
                    <mesh
                      geometry={nodes.Cilindro_121_Mat002_0.geometry}
                      material={nodes.Cilindro_121_Mat002_0.material}
                    />
                  </group>
                  <group position={[132.33, 8.98, 42.15]} rotation={[-2.82, -0.71, -0.18]} scale={[0.41, 0.41, 0.41]}>
                    <mesh
                      geometry={nodes.Cilindro_1_122_Mat001_0.geometry}
                      material={nodes.Cilindro_1_122_Mat001_0.material}
                    />
                  </group>
                  <group position={[49.06, 26.42, -27.67]} rotation={[1.98, 1, -1.31]} scale={[0.46, 0.46, 0.46]}>
                    <mesh
                      geometry={nodes.Cilindro_123_Mat002_0.geometry}
                      material={nodes.Cilindro_123_Mat002_0.material}
                    />
                  </group>
                  <group position={[-21.83, 19.73, 135.17]} rotation={[2.85, 0.08, 2.42]} scale={[1.88, 1.88, 1.88]}>
                    <mesh
                      geometry={nodes.Cilindro_1_124_Mat001_0.geometry}
                      material={nodes.Cilindro_1_124_Mat001_0.material}
                    />
                  </group>
                  <group position={[-101.83, 45.03, -9.76]} rotation={[1.91, 0.52, -2.75]} scale={[0.78, 0.78, 0.78]}>
                    <mesh
                      geometry={nodes.Cilindro_125_Mat002_0.geometry}
                      material={nodes.Cilindro_125_Mat002_0.material}
                    />
                  </group>
                  <group position={[135.73, 17.92, -2.8]} rotation={[-3.13, -1.38, -0.93]} scale={[0.48, 0.48, 0.48]}>
                    <mesh
                      geometry={nodes.Cilindro_1_126_Mat001_0.geometry}
                      material={nodes.Cilindro_1_126_Mat001_0.material}
                    />
                  </group>
                  <group position={[-83.38, 44.38, -62.56]} rotation={[1.51, 0.54, -1.69]} scale={[0.83, 0.83, 0.83]}>
                    <mesh
                      geometry={nodes.Cilindro_127_Mat002_0.geometry}
                      material={nodes.Cilindro_127_Mat002_0.material}
                    />
                  </group>
                  <group position={[-40.85, 18.69, -31.66]} rotation={[2.39, -0.52, -1.13]} scale={[0.33, 0.33, 0.33]}>
                    <mesh
                      geometry={nodes.Cilindro_1_128_Mat001_0.geometry}
                      material={nodes.Cilindro_1_128_Mat001_0.material}
                    />
                  </group>
                  <group position={[63.58, 44.49, 57.35]} rotation={[1.2, 0.03, -0.76]} scale={[0.73, 0.73, 0.73]}>
                    <mesh
                      geometry={nodes.Cilindro_129_Mat002_0.geometry}
                      material={nodes.Cilindro_129_Mat002_0.material}
                    />
                  </group>
                  <group position={[1.61, 45.71, 97.56]} rotation={[1.41, -0.32, -0.3]} scale={[0.73, 0.73, 0.73]}>
                    <mesh
                      geometry={nodes.Cilindro_1_130_Mat001_0.geometry}
                      material={nodes.Cilindro_1_130_Mat001_0.material}
                    />
                  </group>
                  <group position={[-118.75, 25.02, -56.43]} rotation={[0.37, 0.86, 0.3]} scale={[1.09, 1.09, 1.09]}>
                    <mesh
                      geometry={nodes.Cilindro_131_Mat002_0.geometry}
                      material={nodes.Cilindro_131_Mat002_0.material}
                    />
                  </group>
                  <group position={[43.34, 25.67, 39.14]} rotation={[0.42, 0.52, 0.34]} scale={[0.45, 0.45, 0.45]}>
                    <mesh
                      geometry={nodes.Cilindro_1_132_Mat001_0.geometry}
                      material={nodes.Cilindro_1_132_Mat001_0.material}
                    />
                  </group>
                  <group position={[-3.05, 39.03, 73.09]} rotation={[1.22, 0.32, -2.29]} scale={[0.53, 0.53, 0.53]}>
                    <mesh
                      geometry={nodes.Cilindro_133_Mat002_0.geometry}
                      material={nodes.Cilindro_133_Mat002_0.material}
                    />
                  </group>
                  <group position={[-63.98, 6.9, -118.43]} rotation={[-1.82, 0.37, -1.03]} scale={[0.45, 0.45, 0.45]}>
                    <mesh
                      geometry={nodes.Cilindro_1_134_Mat001_0.geometry}
                      material={nodes.Cilindro_1_134_Mat001_0.material}
                    />
                  </group>
                  <group position={[79.31, 24.32, -104.57]} rotation={[0.39, -0.66, -1.59]} scale={[1.12, 1.12, 1.12]}>
                    <mesh
                      geometry={nodes.Cilindro_135_Mat002_0.geometry}
                      material={nodes.Cilindro_135_Mat002_0.material}
                    />
                  </group>
                  <group position={[113.79, 39.54, 30.74]} rotation={[1.96, -0.34, 2.76]}>
                    <mesh
                      geometry={nodes.Cilindro_1_136_Mat001_0.geometry}
                      material={nodes.Cilindro_1_136_Mat001_0.material}
                    />
                  </group>
                  <group position={[-17.44, 16.98, 137.12]} rotation={[3.01, -0.1, 2.03]} scale={[1.88, 1.88, 1.88]}>
                    <mesh
                      geometry={nodes.Cilindro_137_Mat002_0.geometry}
                      material={nodes.Cilindro_137_Mat002_0.material}
                    />
                  </group>
                  <group position={[-93.96, 20.91, 98.01]} rotation={[2.79, 1.07, -2.34]} scale={[1.44, 1.44, 1.44]}>
                    <mesh
                      geometry={nodes.Cilindro_1_138_Mat001_0.geometry}
                      material={nodes.Cilindro_1_138_Mat001_0.material}
                    />
                  </group>
                  <group position={[-87.91, 45.28, 11.32]} rotation={[1.52, -0.42, -0.6]} scale={[0.68, 0.68, 0.68]}>
                    <mesh
                      geometry={nodes.Cilindro_139_Mat002_0.geometry}
                      material={nodes.Cilindro_139_Mat002_0.material}
                    />
                  </group>
                  <group position={[132.84, 25.64, -12.11]} rotation={[0.64, -0.99, -2.58]} scale={[0.84, 0.84, 0.84]}>
                    <mesh
                      geometry={nodes.Cilindro_1_140_Mat001_0.geometry}
                      material={nodes.Cilindro_1_140_Mat001_0.material}
                    />
                  </group>
                  <group position={[-45.66, 18.71, -24.85]} rotation={[2.23, -0.61, -1.71]} scale={[0.39, 0.39, 0.39]}>
                    <mesh
                      geometry={nodes.Cilindro_141_Mat002_0.geometry}
                      material={nodes.Cilindro_141_Mat002_0.material}
                    />
                  </group>
                  <group position={[-61.44, 38.37, 35.49]} rotation={[1.21, -0.06, -1.39]} scale={[0.52, 0.52, 0.52]}>
                    <mesh
                      geometry={nodes.Cilindro_1_142_Mat001_0.geometry}
                      material={nodes.Cilindro_1_142_Mat001_0.material}
                    />
                  </group>
                  <group position={[41.14, 20.74, -32.79]} rotation={[2.37, 0.31, 1.21]} scale={[0.37, 0.37, 0.37]}>
                    <mesh
                      geometry={nodes.Cilindro_143_Mat002_0.geometry}
                      material={nodes.Cilindro_143_Mat002_0.material}
                    />
                  </group>
                  <group position={[-18.54, 38.95, -66.1]} rotation={[1.82, -0.33, 0.66]} scale={[0.55, 0.55, 0.55]}>
                    <mesh
                      geometry={nodes.Cilindro_1_144_Mat001_0.geometry}
                      material={nodes.Cilindro_1_144_Mat001_0.material}
                    />
                  </group>
                  <group position={[9.48, 26.13, -128.19]} rotation={[0.7, 0.16, -2.75]} scale={[1.2, 1.2, 1.2]}>
                    <mesh
                      geometry={nodes.Cilindro_145_Mat002_0.geometry}
                      material={nodes.Cilindro_145_Mat002_0.material}
                    />
                  </group>
                  <group position={[73.89, 31.42, 107.77]} rotation={[1.95, -0.26, -1.79]} scale={[1.2, 1.2, 1.2]}>
                    <mesh
                      geometry={nodes.Cilindro_1_146_Mat001_0.geometry}
                      material={nodes.Cilindro_1_146_Mat001_0.material}
                    />
                  </group>
                  <group position={[111.09, 28.25, -61.48]} rotation={[0.66, -0.63, -2.05]} scale={[1.59, 1.59, 1.59]}>
                    <mesh
                      geometry={nodes.Cilindro_147_Mat002_0.geometry}
                      material={nodes.Cilindro_147_Mat002_0.material}
                    />
                  </group>
                  <group position={[53.51, 45.66, -73.13]} rotation={[1.22, 0.1, -0.08]} scale={[0.66, 0.66, 0.66]}>
                    <mesh
                      geometry={nodes.Cilindro_1_148_Mat001_0.geometry}
                      material={nodes.Cilindro_1_148_Mat001_0.material}
                    />
                  </group>
                  <group position={[-33.55, 44.74, -96.27]} rotation={[1.14, 0.5, -0.95]} scale={[0.94, 0.94, 0.94]}>
                    <mesh
                      geometry={nodes.Cilindro_149_Mat002_0.geometry}
                      material={nodes.Cilindro_149_Mat002_0.material}
                    />
                  </group>
                  <group position={[47.29, 45.6, 80.38]} rotation={[1.65, -0.26, 1.1]} scale={[0.72, 0.72, 0.72]}>
                    <mesh
                      geometry={nodes.Cilindro_1_150_Mat001_0.geometry}
                      material={nodes.Cilindro_1_150_Mat001_0.material}
                    />
                  </group>
                  <group position={[45.24, 29.79, 125.4]} rotation={[2.05, -0.24, -1.83]} scale={[1.33, 1.33, 1.33]}>
                    <mesh
                      geometry={nodes.Cilindro_151_Mat002_0.geometry}
                      material={nodes.Cilindro_151_Mat002_0.material}
                    />
                  </group>
                  <group position={[-43.15, 38.51, -53.02]} rotation={[1.7, -0.26, -2.1]} scale={[0.53, 0.53, 0.53]}>
                    <mesh
                      geometry={nodes.Cilindro_1_152_Mat001_0.geometry}
                      material={nodes.Cilindro_1_152_Mat001_0.material}
                    />
                  </group>
                  <group position={[93.31, 13.89, -99.79]} rotation={[-0.25, -1.1, -0.93]} scale={[0.64, 0.64, 0.64]}>
                    <mesh
                      geometry={nodes.Cilindro_153_Mat002_0.geometry}
                      material={nodes.Cilindro_153_Mat002_0.material}
                    />
                  </group>
                  <group position={[-38.69, 45.72, 88.33]} rotation={[1.97, -0.15, 2.82]} scale={[0.79, 0.79, 0.79]}>
                    <mesh
                      geometry={nodes.Cilindro_1_154_Mat001_0.geometry}
                      material={nodes.Cilindro_1_154_Mat001_0.material}
                    />
                  </group>
                  <group position={[16.92, 40.32, -68.95]} rotation={[2.35, 0.47, -2.86]} scale={[0.51, 0.51, 0.51]}>
                    <mesh
                      geometry={nodes.Cilindro_155_Mat002_0.geometry}
                      material={nodes.Cilindro_155_Mat002_0.material}
                    />
                  </group>
                  <group position={[-105.37, 27.54, 78.27]} rotation={[2.47, 0.42, 0.69]} scale={[1.76, 1.76, 1.76]}>
                    <mesh
                      geometry={nodes.Cilindro_1_156_Mat001_0.geometry}
                      material={nodes.Cilindro_1_156_Mat001_0.material}
                    />
                  </group>
                  <group position={[-28.89, 16.26, 45.71]} rotation={[0.07, -0.92, 0.81]} scale={[0.28, 0.28, 0.28]}>
                    <mesh
                      geometry={nodes.Cilindro_157_Mat002_0.geometry}
                      material={nodes.Cilindro_157_Mat002_0.material}
                    />
                  </group>
                  <group position={[49.78, 43.35, -94.91]} rotation={[1.11, 0.15, -2.11]} scale={[0.81, 0.81, 0.81]}>
                    <mesh
                      geometry={nodes.Cilindro_1_158_Mat001_0.geometry}
                      material={nodes.Cilindro_1_158_Mat001_0.material}
                    />
                  </group>
                  <group position={[-43.24, 13.49, -26.42]} rotation={[2.36, -1.23, -0.16]} scale={[0.21, 0.21, 0.21]}>
                    <mesh
                      geometry={nodes.Cilindro_159_Mat002_0.geometry}
                      material={nodes.Cilindro_159_Mat002_0.material}
                    />
                  </group>
                  <group position={[-77.38, 45.54, 63.38]} rotation={[1.25, -0.07, 0.28]} scale={[0.7, 0.7, 0.7]}>
                    <mesh
                      geometry={nodes.Cilindro_1_160_Mat001_0.geometry}
                      material={nodes.Cilindro_1_160_Mat001_0.material}
                    />
                  </group>
                  <group position={[9.76, 12.04, -49.4]} rotation={[-2.69, 0.28, -1.69]} scale={[0.16, 0.16, 0.16]}>
                    <mesh
                      geometry={nodes.Cilindro_161_Mat002_0.geometry}
                      material={nodes.Cilindro_161_Mat002_0.material}
                    />
                  </group>
                  <group position={[16.88, 43.11, 110.75]} rotation={[1.84, -0.37, -0.04]} scale={[0.88, 0.88, 0.88]}>
                    <mesh
                      geometry={nodes.Cilindro_1_162_Mat001_0.geometry}
                      material={nodes.Cilindro_1_162_Mat001_0.material}
                    />
                  </group>
                  <group position={[0.87, 21.12, 137.03]} rotation={[2.83, -0.34, 0.82]} scale={[1.39, 1.39, 1.39]}>
                    <mesh
                      geometry={nodes.Cilindro_163_Mat002_0.geometry}
                      material={nodes.Cilindro_163_Mat002_0.material}
                    />
                  </group>
                  <group position={[133.88, 14.91, -13.79]} rotation={[-1.43, -0.22, -2.5]} scale={[0.39, 0.39, 0.39]}>
                    <mesh
                      geometry={nodes.Cilindro_1_164_Mat001_0.geometry}
                      material={nodes.Cilindro_1_164_Mat001_0.material}
                    />
                  </group>
                  <group position={[-68.14, 43.57, -41.3]} rotation={[1.29, -0.16, -0.18]} scale={[0.58, 0.58, 0.58]}>
                    <mesh
                      geometry={nodes.Cilindro_165_Mat002_0.geometry}
                      material={nodes.Cilindro_165_Mat002_0.material}
                    />
                  </group>
                  <group position={[35.64, 38.52, -58.15]} rotation={[1.97, -0.15, 0.34]} scale={[0.61, 0.61, 0.61]}>
                    <mesh
                      geometry={nodes.Cilindro_1_166_Mat001_0.geometry}
                      material={nodes.Cilindro_1_166_Mat001_0.material}
                    />
                  </group>
                  <group position={[35.59, 38.97, 115.64]} rotation={[1.83, -0.41, -0.27]} scale={[0.97, 0.97, 0.97]}>
                    <mesh
                      geometry={nodes.Cilindro_167_Mat002_0.geometry}
                      material={nodes.Cilindro_167_Mat002_0.material}
                    />
                  </group>
                  <group position={[-33.62, 20.18, 44.16]} rotation={[0.56, -0.61, 2.03]} scale={[0.38, 0.38, 0.38]}>
                    <mesh
                      geometry={nodes.Cilindro_1_168_Mat001_0.geometry}
                      material={nodes.Cilindro_1_168_Mat001_0.material}
                    />
                  </group>
                  <group position={[-48.93, 28.78, 35.62]} rotation={[1.2, -0.6, -2.81]} scale={[0.47, 0.47, 0.47]}>
                    <mesh
                      geometry={nodes.Cilindro_169_Mat002_0.geometry}
                      material={nodes.Cilindro_169_Mat002_0.material}
                    />
                  </group>
                  <group position={[33.56, 13.87, 41.72]} rotation={[-0.12, 0.36, 2.67]} scale={[0.18, 0.18, 0.18]}>
                    <mesh
                      geometry={nodes.Cilindro_1_170_Mat001_0.geometry}
                      material={nodes.Cilindro_1_170_Mat001_0.material}
                    />
                  </group>
                  <group position={[-72.2, 40.02, -5.54]} rotation={[1.63, -0.73, 1.67]} scale={[0.71, 0.71, 0.71]}>
                    <mesh
                      geometry={nodes.Cilindro_171_Mat002_0.geometry}
                      material={nodes.Cilindro_171_Mat002_0.material}
                    />
                  </group>
                  <group position={[104.36, 42.71, 39.84]} rotation={[1.79, -0.2, -0.83]} scale={[1.08, 1.08, 1.08]}>
                    <mesh
                      geometry={nodes.Cilindro_1_172_Mat001_0.geometry}
                      material={nodes.Cilindro_1_172_Mat001_0.material}
                    />
                  </group>
                  <group position={[-112.61, 42.02, 1.77]} rotation={[1.65, 0.63, -1.22]} scale={[0.91, 0.91, 0.91]}>
                    <mesh
                      geometry={nodes.Cilindro_173_Mat002_0.geometry}
                      material={nodes.Cilindro_173_Mat002_0.material}
                    />
                  </group>
                  <group position={[-49.4, 45.37, 76.3]} rotation={[1.66, -0.17, 2.45]} scale={[0.73, 0.73, 0.73]}>
                    <mesh
                      geometry={nodes.Cilindro_1_174_Mat001_0.geometry}
                      material={nodes.Cilindro_1_174_Mat001_0.material}
                    />
                  </group>
                  <group position={[-85.76, 37.86, -81.1]} rotation={[1.33, 0.2, 3.14]} scale={[1.08, 1.08, 1.08]}>
                    <mesh
                      geometry={nodes.Cilindro_175_Mat002_0.geometry}
                      material={nodes.Cilindro_175_Mat002_0.material}
                    />
                  </group>
                  <group position={[135.97, 8.3, 21.25]} rotation={[-1.27, -0.29, -0.63]} scale={[0.44, 0.44, 0.44]}>
                    <mesh
                      geometry={nodes.Cilindro_1_176_Mat001_0.geometry}
                      material={nodes.Cilindro_1_176_Mat001_0.material}
                    />
                  </group>
                  <group position={[-96.18, 43.36, -49.3]} rotation={[1.65, 0.01, 1.62]} scale={[0.82, 0.82, 0.82]}>
                    <mesh
                      geometry={nodes.Cilindro_177_Mat002_0.geometry}
                      material={nodes.Cilindro_177_Mat002_0.material}
                    />
                  </group>
                  <group position={[-48.04, 19.62, 25.74]} rotation={[0.66, -1.21, 2.38]} scale={[0.39, 0.39, 0.39]}>
                    <mesh
                      geometry={nodes.Cilindro_1_178_Mat001_0.geometry}
                      material={nodes.Cilindro_1_178_Mat001_0.material}
                    />
                  </group>
                  <group position={[-78.73, 7.56, 117.58]} rotation={[-3.08, 0.6, -2.3]} scale={[0.93, 0.93, 0.93]}>
                    <mesh
                      geometry={nodes.Cilindro_179_Mat002_0.geometry}
                      material={nodes.Cilindro_179_Mat002_0.material}
                    />
                  </group>
                  <group position={[45.56, 27.64, 38.67]} rotation={[1.14, 0.98, -1.45]} scale={[0.47, 0.47, 0.47]}>
                    <mesh
                      geometry={nodes.Cilindro_1_180_Mat001_0.geometry}
                      material={nodes.Cilindro_1_180_Mat001_0.material}
                    />
                  </group>
                  <group position={[4.57, 43.4, -77.98]} rotation={[2.05, 0.35, -0.59]} scale={[0.6, 0.6, 0.6]}>
                    <mesh
                      geometry={nodes.Cilindro_181_Mat002_0.geometry}
                      material={nodes.Cilindro_181_Mat002_0.material}
                    />
                  </group>
                  <group position={[-46.17, 41.95, 105.12]} rotation={[2.26, -0.03, 2.15]} scale={[0.83, 0.83, 0.83]}>
                    <mesh
                      geometry={nodes.Cilindro_1_182_Mat001_0.geometry}
                      material={nodes.Cilindro_1_182_Mat001_0.material}
                    />
                  </group>
                  <group position={[-53.1, 45.22, 72.33]} rotation={[1.26, -0.03, -0.04]} scale={[0.85, 0.85, 0.85]}>
                    <mesh
                      geometry={nodes.Cilindro_183_Mat002_0.geometry}
                      material={nodes.Cilindro_183_Mat002_0.material}
                    />
                  </group>
                  <group position={[-54.09, 25.76, 20.19]} rotation={[0.81, -1.19, 1.38]} scale={[0.43, 0.43, 0.43]}>
                    <mesh
                      geometry={nodes.Cilindro_1_184_Mat001_0.geometry}
                      material={nodes.Cilindro_1_184_Mat001_0.material}
                    />
                  </group>
                  <group position={[76.81, 14.57, 117.52]} rotation={[2.94, -0.52, 1.8]} scale={[0.73, 0.73, 0.73]}>
                    <mesh
                      geometry={nodes.Cilindro_185_Mat002_0.geometry}
                      material={nodes.Cilindro_185_Mat002_0.material}
                    />
                  </group>
                  <group position={[-34.36, 38.31, 116.71]} rotation={[2.3, 0.24, 1.19]} scale={[1.02, 1.02, 1.02]}>
                    <mesh
                      geometry={nodes.Cilindro_1_186_Mat001_0.geometry}
                      material={nodes.Cilindro_1_186_Mat001_0.material}
                    />
                  </group>
                  <group position={[87.53, 45.22, -48.88]} rotation={[1.05, -0.19, -1.33]} scale={[0.81, 0.81, 0.81]}>
                    <mesh
                      geometry={nodes.Cilindro_187_Mat002_0.geometry}
                      material={nodes.Cilindro_187_Mat002_0.material}
                    />
                  </group>
                  <group position={[-87.93, 45.61, 27.55]} rotation={[1.74, -0.15, 2.41]} scale={[0.65, 0.65, 0.65]}>
                    <mesh
                      geometry={nodes.Cilindro_1_188_Mat001_0.geometry}
                      material={nodes.Cilindro_1_188_Mat001_0.material}
                    />
                  </group>
                  <group position={[7.38, 28.65, 60.9]} rotation={[0.79, -0.16, 1.32]} scale={[0.42, 0.42, 0.42]}>
                    <mesh
                      geometry={nodes.Cilindro_189_Mat002_0.geometry}
                      material={nodes.Cilindro_189_Mat002_0.material}
                    />
                  </group>
                  <group position={[-116.32, 11.07, -74.6]} rotation={[-0.16, 1, 0.4]} scale={[0.76, 0.76, 0.76]}>
                    <mesh
                      geometry={nodes.Cilindro_1_190_Mat001_0.geometry}
                      material={nodes.Cilindro_1_190_Mat001_0.material}
                    />
                  </group>
                  <group position={[105.02, 44.06, 21.76]} rotation={[1.86, -0.22, -0.47]} scale={[0.79, 0.79, 0.79]}>
                    <mesh
                      geometry={nodes.Cilindro_191_Mat002_0.geometry}
                      material={nodes.Cilindro_191_Mat002_0.material}
                    />
                  </group>
                  <group position={[78.89, 21.22, -107.48]} rotation={[0.78, -0.48, -0.13]} scale={[1.18, 1.18, 1.18]}>
                    <mesh
                      geometry={nodes.Cilindro_1_192_Mat001_0.geometry}
                      material={nodes.Cilindro_1_192_Mat001_0.material}
                    />
                  </group>
                  <group position={[-121.31, 34.77, -17.92]} rotation={[0.82, 0.89, -1.31]} scale={[1.2, 1.2, 1.2]}>
                    <mesh
                      geometry={nodes.Cilindro_193_Mat002_0.geometry}
                      material={nodes.Cilindro_193_Mat002_0.material}
                    />
                  </group>
                  <group position={[-40, 25.31, -122.76]} rotation={[0.91, 0.32, 2.85]} scale={[1.24, 1.24, 1.24]}>
                    <mesh
                      geometry={nodes.Cilindro_1_194_Mat001_0.geometry}
                      material={nodes.Cilindro_1_194_Mat001_0.material}
                    />
                  </group>
                  <group position={[-79.37, 27.63, 105.47]} rotation={[2.12, 0.63, -0.41]} scale={[1.67, 1.67, 1.67]}>
                    <mesh
                      geometry={nodes.Cilindro_195_Mat002_0.geometry}
                      material={nodes.Cilindro_195_Mat002_0.material}
                    />
                  </group>
                  <group position={[-121.18, 20.6, 62.86]} rotation={[2.42, 0.67, 3.14]} scale={[1.25, 1.25, 1.25]}>
                    <mesh
                      geometry={nodes.Cilindro_1_196_Mat001_0.geometry}
                      material={nodes.Cilindro_1_196_Mat001_0.material}
                    />
                  </group>
                  <group position={[50.17, 44.48, -65.27]} rotation={[1.76, 0.2, -1.5]} scale={[0.72, 0.72, 0.72]}>
                    <mesh
                      geometry={nodes.Cilindro_197_Mat002_0.geometry}
                      material={nodes.Cilindro_197_Mat002_0.material}
                    />
                  </group>
                  <group position={[-81.24, 16.52, 111.39]} rotation={[2.2, 0.6, -1.81]} scale={[1.43, 1.43, 1.43]}>
                    <mesh
                      geometry={nodes.Cilindro_1_198_Mat001_0.geometry}
                      material={nodes.Cilindro_1_198_Mat001_0.material}
                    />
                  </group>
                  <group position={[67.44, 42.11, -87.7]} rotation={[0.9, -0.04, -1.29]} scale={[0.93, 0.93, 0.93]}>
                    <mesh
                      geometry={nodes.Cilindro_199_Mat002_0.geometry}
                      material={nodes.Cilindro_199_Mat002_0.material}
                    />
                  </group>
                </group>
              </group>
              <group position={[-165.21, -6.23, -6.15]} rotation={[1.64, 0.01, 0.18]}>
                <group position={[0, 0, 0.74]}>
                  <mesh geometry={nodes.DONA_4_Mat_0.geometry} material={nodes.DONA_4_Mat_0.material} />
                  <mesh geometry={nodes.CHOC_4_Mat003_0.geometry} material={materials['Mat.003']} />
                </group>
                <group position={[0, 0, -1.48]}>
                  <group position={[-27.1, 32.72, -54.46]} rotation={[2.05, -0.13, 2.21]} scale={[0.48, 0.48, 0.48]}>
                    <mesh
                      geometry={nodes.Cilindro_1_0_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_0_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[72.59, 45.34, -48.82]} rotation={[1.8, 0.05, 0.56]} scale={[0.7, 0.7, 0.7]}>
                    <mesh
                      geometry={nodes.Cilindro_1_2_2_Mat002_0.geometry}
                      material={nodes.Cilindro_1_2_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[105.41, 43.86, 23.45]} rotation={[1.73, 0.07, -0.38]} scale={[0.77, 0.77, 0.77]}>
                    <mesh
                      geometry={nodes.Cilindro_1_2_3_Mat001_0.geometry}
                      material={nodes.Cilindro_1_2_3_Mat001_0.material}
                    />
                  </group>
                  <group position={[25.98, 33.35, -119.52]} rotation={[0.92, 0.21, -0.78]} scale={[1.21, 1.21, 1.21]}>
                    <mesh
                      geometry={nodes.Cilindro_3_2_Mat002_0.geometry}
                      material={nodes.Cilindro_3_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[28.3, 42.61, -70.6]} rotation={[1.96, 0.45, -0.64]} scale={[0.64, 0.64, 0.64]}>
                    <mesh
                      geometry={nodes.Cilindro_1_4_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_4_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-69.64, 45.55, 60.52]} rotation={[1.92, 0.03, -1.29]} scale={[0.68, 0.68, 0.68]}>
                    <mesh
                      geometry={nodes.Cilindro_5_2_Mat002_0.geometry}
                      material={nodes.Cilindro_5_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[-47.09, 44.07, -93.62]} rotation={[1.4, -0.22, 2.78]} scale={[0.82, 0.82, 0.82]}>
                    <mesh
                      geometry={nodes.Cilindro_1_6_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_6_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-47.09, 39.29, -105.47]} rotation={[0.62, 0.05, -0.13]} scale={[0.94, 0.94, 0.94]}>
                    <mesh
                      geometry={nodes.Cilindro_7_2_Mat002_0.geometry}
                      material={nodes.Cilindro_7_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[81.5, 45.4, -34.26]} rotation={[1.29, -0.07, 1.57]} scale={[0.63, 0.63, 0.63]}>
                    <mesh
                      geometry={nodes.Cilindro_1_8_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_8_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-76.32, 21.93, 111.54]} rotation={[2.69, 0.47, -2.51]} scale={[2, 2, 2]}>
                    <mesh
                      geometry={nodes.Cilindro_9_2_Mat002_0.geometry}
                      material={nodes.Cilindro_9_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[35.43, 45.59, -81.89]} rotation={[1.37, -0.11, 1.29]} scale={[0.68, 0.68, 0.68]}>
                    <mesh
                      geometry={nodes.Cilindro_1_10_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_10_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[42.64, 44.84, 76.59]} rotation={[1.2, 0.39, -2.65]} scale={[0.73, 0.73, 0.73]}>
                    <mesh
                      geometry={nodes.Cilindro_11_2_Mat002_0.geometry}
                      material={nodes.Cilindro_11_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[24.9, 33.88, 125.24]} rotation={[2.13, -0.12, 2.97]} scale={1.09}>
                    <mesh
                      geometry={nodes.Cilindro_1_12_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_12_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-99.2, 43.7, -40.62]} rotation={[1.68, 0.06, 1.77]} scale={[0.83, 0.83, 0.83]}>
                    <mesh
                      geometry={nodes.Cilindro_13_Mat002_0.geometry}
                      material={nodes.Cilindro_13_Mat002_0.material}
                    />
                  </group>
                  <group position={[-79.39, 41.8, 82.81]} rotation={[2.02, 0.48, -1.94]} scale={[0.8, 0.8, 0.8]}>
                    <mesh
                      geometry={nodes.Cilindro_1_14_Mat001_0.geometry}
                      material={nodes.Cilindro_1_14_Mat001_0.material}
                    />
                  </group>
                  <group position={[-35.14, 35.91, 119.96]} rotation={[2.18, 0.09, 2.7]} scale={[0.92, 0.92, 0.92]}>
                    <mesh
                      geometry={nodes.Cilindro_15_Mat002_0.geometry}
                      material={nodes.Cilindro_15_Mat002_0.material}
                    />
                  </group>
                  <group position={[67.72, 33.91, -102.14]} rotation={[0.73, -0.55, 1.33]} scale={[1.41, 1.41, 1.41]}>
                    <mesh
                      geometry={nodes.Cilindro_1_16_Mat001_0.geometry}
                      material={nodes.Cilindro_1_16_Mat001_0.material}
                    />
                  </group>
                  <group position={[24.66, 37.6, 120.27]} rotation={[2.27, -0.24, -1.22]} scale={[0.99, 0.99, 0.99]}>
                    <mesh
                      geometry={nodes.Cilindro_17_Mat002_0.geometry}
                      material={nodes.Cilindro_17_Mat002_0.material}
                    />
                  </group>
                  <group position={[72.38, 39.09, -91.08]} rotation={[1.18, -0.3, -1.76]} scale={[0.99, 0.99, 0.99]}>
                    <mesh
                      geometry={nodes.Cilindro_1_18_Mat001_0.geometry}
                      material={nodes.Cilindro_1_18_Mat001_0.material}
                    />
                  </group>
                  <group position={[113.75, 6.9, -74.38]} rotation={[-1.39, -0.24, -0.44]} scale={[0.49, 0.49, 0.49]}>
                    <mesh
                      geometry={nodes.Cilindro_19_Mat002_0.geometry}
                      material={nodes.Cilindro_19_Mat002_0.material}
                    />
                  </group>
                  <group position={[121.94, 30.04, 44.16]} rotation={[1.6, -0.61, -0.37]}>
                    <mesh
                      geometry={nodes.Cilindro_1_20_Mat001_0.geometry}
                      material={nodes.Cilindro_1_20_Mat001_0.material}
                    />
                  </group>
                  <group position={[127.61, 28.4, 22.12]} rotation={[1.55, -0.83, -0.79]} scale={[1.31, 1.31, 1.31]}>
                    <mesh
                      geometry={nodes.Cilindro_21_Mat002_0.geometry}
                      material={nodes.Cilindro_21_Mat002_0.material}
                    />
                  </group>
                  <group position={[-101.54, 2.74, 93.64]} rotation={[-1.82, -0.32, 0.25]} scale={[0.47, 0.47, 0.47]}>
                    <mesh
                      geometry={nodes.Cilindro_1_22_Mat001_0.geometry}
                      material={nodes.Cilindro_1_22_Mat001_0.material}
                    />
                  </group>
                  <group position={[-24.53, 41.21, 73.02]} rotation={[1.05, 0.09, -0.62]} scale={[0.67, 0.67, 0.67]}>
                    <mesh
                      geometry={nodes.Cilindro_23_Mat002_0.geometry}
                      material={nodes.Cilindro_23_Mat002_0.material}
                    />
                  </group>
                  <group position={[-125.15, 22.52, -45.74]} rotation={[1.56, 1.22, -2.3]} scale={[1.22, 1.22, 1.22]}>
                    <mesh
                      geometry={nodes.Cilindro_1_24_Mat001_0.geometry}
                      material={nodes.Cilindro_1_24_Mat001_0.material}
                    />
                  </group>
                  <group position={[-118.45, 24.09, -58.4]} rotation={[0.55, 0.81, 0.34]} scale={[1.11, 1.11, 1.11]}>
                    <mesh
                      geometry={nodes.Cilindro_25_Mat002_0.geometry}
                      material={nodes.Cilindro_25_Mat002_0.material}
                    />
                  </group>
                  <group position={[127.59, 32.21, -12.02]} rotation={[1.35, -0.58, -0.8]} scale={[0.78, 0.78, 0.78]}>
                    <mesh
                      geometry={nodes.Cilindro_1_26_Mat001_0.geometry}
                      material={nodes.Cilindro_1_26_Mat001_0.material}
                    />
                  </group>
                  <group position={[112.67, 37.01, 48.53]} rotation={[1.67, -0.37, -2.01]} scale={[0.91, 0.91, 0.91]}>
                    <mesh
                      geometry={nodes.Cilindro_27_Mat002_0.geometry}
                      material={nodes.Cilindro_27_Mat002_0.material}
                    />
                  </group>
                  <group position={[53.52, 27.94, 26.03]} rotation={[1.26, 0.52, 2.85]} scale={[0.52, 0.52, 0.52]}>
                    <mesh
                      geometry={nodes.Cilindro_1_28_Mat001_0.geometry}
                      material={nodes.Cilindro_1_28_Mat001_0.material}
                    />
                  </group>
                  <group position={[-86.08, 43.09, 70.55]} rotation={[1.55, 0.3, 0.37]} scale={[0.8, 0.8, 0.8]}>
                    <mesh
                      geometry={nodes.Cilindro_29_Mat002_0.geometry}
                      material={nodes.Cilindro_29_Mat002_0.material}
                    />
                  </group>
                  <group position={[133.85, 13.23, 35.97]} rotation={[2.29, -0.8, -1.88]} scale={[1.07, 1.07, 1.07]}>
                    <mesh
                      geometry={nodes.Cilindro_1_30_Mat001_0.geometry}
                      material={nodes.Cilindro_1_30_Mat001_0.material}
                    />
                  </group>
                  <group position={[-115.1, 16.33, -72.92]} rotation={[0.94, 0.57, 1.8]} scale={[1.17, 1.17, 1.17]}>
                    <mesh
                      geometry={nodes.Cilindro_31_Mat002_0.geometry}
                      material={nodes.Cilindro_31_Mat002_0.material}
                    />
                  </group>
                  <group position={[-57.73, 26.94, 5.51]} rotation={[1.81, -0.95, 2.74]} scale={[0.41, 0.41, 0.41]}>
                    <mesh
                      geometry={nodes.Cilindro_1_32_Mat001_0.geometry}
                      material={nodes.Cilindro_1_32_Mat001_0.material}
                    />
                  </group>
                  <group position={[-82.26, 45.56, -51.9]} rotation={[1.42, -0.18, 1.14]} scale={[0.97, 0.97, 0.97]}>
                    <mesh
                      geometry={nodes.Cilindro_33_Mat002_0.geometry}
                      material={nodes.Cilindro_33_Mat002_0.material}
                    />
                  </group>
                  <group position={[68.81, 27.6, 114.73]} rotation={[2.34, -0.18, 1.82]} scale={[1.32, 1.32, 1.32]}>
                    <mesh
                      geometry={nodes.Cilindro_1_34_Mat001_0.geometry}
                      material={nodes.Cilindro_1_34_Mat001_0.material}
                    />
                  </group>
                  <group position={[73.15, 42.33, 27.64]} rotation={[1.09, 0.25, 0.59]} scale={[0.64, 0.64, 0.64]}>
                    <mesh
                      geometry={nodes.Cilindro_35_Mat002_0.geometry}
                      material={nodes.Cilindro_35_Mat002_0.material}
                    />
                  </group>
                  <group position={[69.75, 45.55, 60.31]} rotation={[1.61, -0.2, -3.07]} scale={[0.67, 0.67, 0.67]}>
                    <mesh
                      geometry={nodes.Cilindro_1_36_Mat001_0.geometry}
                      material={nodes.Cilindro_1_36_Mat001_0.material}
                    />
                  </group>
                  <group position={[-47.34, 44.6, 95.61]} rotation={[2.13, 0.11, -1.74]} scale={[0.78, 0.78, 0.78]}>
                    <mesh
                      geometry={nodes.Cilindro_37_Mat002_0.geometry}
                      material={nodes.Cilindro_37_Mat002_0.material}
                    />
                  </group>
                  <group position={[-98.51, 45.19, 26.86]} rotation={[1.49, 0.48, -2.22]} scale={[0.73, 0.73, 0.73]}>
                    <mesh
                      geometry={nodes.Cilindro_1_38_Mat001_0.geometry}
                      material={nodes.Cilindro_1_38_Mat001_0.material}
                    />
                  </group>
                  <group position={[-110.53, 19.58, -76.57]} rotation={[0.69, 0.85, -0.19]} scale={[1.41, 1.41, 1.41]}>
                    <mesh
                      geometry={nodes.Cilindro_39_Mat002_0.geometry}
                      material={nodes.Cilindro_39_Mat002_0.material}
                    />
                  </group>
                  <group position={[88.83, 40.75, 75.76]} rotation={[1.98, -0.04, 3.02]} scale={[0.88, 0.88, 0.88]}>
                    <mesh
                      geometry={nodes.Cilindro_1_40_Mat001_0.geometry}
                      material={nodes.Cilindro_1_40_Mat001_0.material}
                    />
                  </group>
                  <group position={[-78.52, 24.41, 108.38]} rotation={[2.78, 0.87, -2.01]} scale={[1.8, 1.8, 1.8]}>
                    <mesh
                      geometry={nodes.Cilindro_41_Mat002_0.geometry}
                      material={nodes.Cilindro_41_Mat002_0.material}
                    />
                  </group>
                  <group position={[-86.19, 45.31, 22.58]} rotation={[1.17, -0.27, 0.51]} scale={[0.62, 0.62, 0.62]}>
                    <mesh
                      geometry={nodes.Cilindro_1_42_Mat001_0.geometry}
                      material={nodes.Cilindro_1_42_Mat001_0.material}
                    />
                  </group>
                  <group position={[-111.46, 42.23, 14.55]} rotation={[1.27, 0.58, -1.43]} scale={[0.8, 0.8, 0.8]}>
                    <mesh
                      geometry={nodes.Cilindro_43_Mat002_0.geometry}
                      material={nodes.Cilindro_43_Mat002_0.material}
                    />
                  </group>
                  <group position={[-31.16, 16.7, -131.39]} rotation={[0.68, 0.42, 3.03]}>
                    <mesh
                      geometry={nodes.Cilindro_1_44_Mat001_0.geometry}
                      material={nodes.Cilindro_1_44_Mat001_0.material}
                    />
                  </group>
                  <group position={[25.34, 33.1, 60.14]} rotation={[0.63, 0.47, 0.75]} scale={[0.49, 0.49, 0.49]}>
                    <mesh
                      geometry={nodes.Cilindro_45_Mat002_0.geometry}
                      material={nodes.Cilindro_45_Mat002_0.material}
                    />
                  </group>
                  <group position={[43.99, 45.68, 88.1]} rotation={[1.49, -0.06, -1.17]} scale={[0.93, 0.93, 0.93]}>
                    <mesh
                      geometry={nodes.Cilindro_1_46_Mat001_0.geometry}
                      material={nodes.Cilindro_1_46_Mat001_0.material}
                    />
                  </group>
                  <group position={[7.14, 45.18, -85.15]} rotation={[2.01, 0.21, -2.44]} scale={[0.74, 0.74, 0.74]}>
                    <mesh
                      geometry={nodes.Cilindro_47_Mat002_0.geometry}
                      material={nodes.Cilindro_47_Mat002_0.material}
                    />
                  </group>
                  <group position={[30.38, 45.53, -91.83]} rotation={[1.91, -0.23, 2.86]} scale={[0.83, 0.83, 0.83]}>
                    <mesh
                      geometry={nodes.Cilindro_1_48_Mat001_0.geometry}
                      material={nodes.Cilindro_1_48_Mat001_0.material}
                    />
                  </group>
                  <group position={[-92.19, 45.71, 19.94]} rotation={[1.81, 0.06, -2.93]} scale={[0.68, 0.68, 0.68]}>
                    <mesh
                      geometry={nodes.Cilindro_49_Mat002_0.geometry}
                      material={nodes.Cilindro_49_Mat002_0.material}
                    />
                  </group>
                  <group position={[-122.07, 7.51, 64.44]} rotation={[-1.94, 0.07, 0.63]} scale={[0.42, 0.42, 0.42]}>
                    <mesh
                      geometry={nodes.Cilindro_1_50_Mat001_0.geometry}
                      material={nodes.Cilindro_1_50_Mat001_0.material}
                    />
                  </group>
                  <group position={[-10.91, 18.74, -49.74]} rotation={[2.62, -0.04, -1.19]} scale={[0.4, 0.4, 0.4]}>
                    <mesh
                      geometry={nodes.Cilindro_51_Mat002_0.geometry}
                      material={nodes.Cilindro_51_Mat002_0.material}
                    />
                  </group>
                  <group position={[-70.01, 15.93, -115.99]} rotation={[0.69, 0.06, 1.97]} scale={[1.02, 1.02, 1.02]}>
                    <mesh
                      geometry={nodes.Cilindro_1_52_Mat001_0.geometry}
                      material={nodes.Cilindro_1_52_Mat001_0.material}
                    />
                  </group>
                  <group position={[-99.89, 15.06, 95.28]} rotation={[2.21, 0.8, 1.23]} scale={[1.91, 1.91, 1.91]}>
                    <mesh
                      geometry={nodes.Cilindro_53_Mat002_0.geometry}
                      material={nodes.Cilindro_53_Mat002_0.material}
                    />
                  </group>
                  <group position={[128.29, 18.67, 49.41]} rotation={[1.51, -0.98, -1.2]} scale={[1.13, 1.13, 1.13]}>
                    <mesh
                      geometry={nodes.Cilindro_1_54_Mat001_0.geometry}
                      material={nodes.Cilindro_1_54_Mat001_0.material}
                    />
                  </group>
                  <group position={[-75.51, 45.61, -60.09]} rotation={[1.79, -0.11, 2.69]} scale={[0.75, 0.75, 0.75]}>
                    <mesh
                      geometry={nodes.Cilindro_55_Mat002_0.geometry}
                      material={nodes.Cilindro_55_Mat002_0.material}
                    />
                  </group>
                  <group position={[-88.15, 44.99, -50.63]} rotation={[1.67, 0.33, -1.67]} scale={[0.74, 0.74, 0.74]}>
                    <mesh
                      geometry={nodes.Cilindro_1_56_Mat001_0.geometry}
                      material={nodes.Cilindro_1_56_Mat001_0.material}
                    />
                  </group>
                  <group position={[96.22, 11.54, 104.44]} rotation={[2.92, -0.78, -1.14]} scale={[0.94, 0.94, 0.94]}>
                    <mesh
                      geometry={nodes.Cilindro_57_Mat002_0.geometry}
                      material={nodes.Cilindro_57_Mat002_0.material}
                    />
                  </group>
                  <group position={[-41.09, 26.1, -37.61]} rotation={[2.78, -0.57, -2.56]} scale={[0.47, 0.47, 0.47]}>
                    <mesh
                      geometry={nodes.Cilindro_1_58_Mat001_0.geometry}
                      material={nodes.Cilindro_1_58_Mat001_0.material}
                    />
                  </group>
                  <group position={[130.79, 27.21, -17.03]} rotation={[1.55, -1.26, 2.1]} scale={[1.01, 1.01, 1.01]}>
                    <mesh
                      geometry={nodes.Cilindro_59_Mat002_0.geometry}
                      material={nodes.Cilindro_59_Mat002_0.material}
                    />
                  </group>
                  <group position={[-123.91, 26.95, -40.37]} rotation={[0.98, 0.55, 1.11]} scale={[1.17, 1.17, 1.17]}>
                    <mesh
                      geometry={nodes.Cilindro_1_60_Mat001_0.geometry}
                      material={nodes.Cilindro_1_60_Mat001_0.material}
                    />
                  </group>
                  <group position={[26.7, 42.2, 111.2]} rotation={[2.24, -0.16, 3.12]} scale={[0.89, 0.89, 0.89]}>
                    <mesh
                      geometry={nodes.Cilindro_61_Mat002_0.geometry}
                      material={nodes.Cilindro_61_Mat002_0.material}
                    />
                  </group>
                  <group position={[21.64, 38.24, 68.46]} rotation={[1.34, 0.28, -2.5]} scale={[0.5, 0.5, 0.5]}>
                    <mesh
                      geometry={nodes.Cilindro_1_62_Mat001_0.geometry}
                      material={nodes.Cilindro_1_62_Mat001_0.material}
                    />
                  </group>
                  <group position={[-105.42, 40.95, -43.57]} rotation={[1.02, 0.54, -1.73]} scale={[0.9, 0.9, 0.9]}>
                    <mesh
                      geometry={nodes.Cilindro_63_Mat002_0.geometry}
                      material={nodes.Cilindro_63_Mat002_0.material}
                    />
                  </group>
                  <group position={[40.52, 39.52, 113.2]} rotation={[1.97, 0.23, -0.91]} scale={[0.89, 0.89, 0.89]}>
                    <mesh
                      geometry={nodes.Cilindro_1_64_Mat001_0.geometry}
                      material={nodes.Cilindro_1_64_Mat001_0.material}
                    />
                  </group>
                  <group position={[102.92, 43.99, 31.73]} rotation={[1.9, -0.06, 2.96]} scale={[0.78, 0.78, 0.78]}>
                    <mesh
                      geometry={nodes.Cilindro_65_Mat002_0.geometry}
                      material={nodes.Cilindro_65_Mat002_0.material}
                    />
                  </group>
                  <group position={[104.48, 44.2, -17.53]} rotation={[1.41, -0.56, 1.87]} scale={[0.83, 0.83, 0.83]}>
                    <mesh
                      geometry={nodes.Cilindro_1_66_Mat001_0.geometry}
                      material={nodes.Cilindro_1_66_Mat001_0.material}
                    />
                  </group>
                  <group position={[-21.43, 29.67, 58.25]} rotation={[0.6, -0.02, -2.46]} scale={[0.45, 0.45, 0.45]}>
                    <mesh
                      geometry={nodes.Cilindro_67_Mat002_0.geometry}
                      material={nodes.Cilindro_67_Mat002_0.material}
                    />
                  </group>
                  <group position={[113.79, 39.54, 30.74]} rotation={[1.96, -0.34, 2.76]}>
                    <mesh
                      geometry={nodes.Cilindro_1_136_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_136_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-17.44, 16.98, 137.12]} rotation={[3.01, -0.1, 2.03]} scale={[1.88, 1.88, 1.88]}>
                    <mesh
                      geometry={nodes.Cilindro_137_2_Mat002_0.geometry}
                      material={nodes.Cilindro_137_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[-93.96, 20.91, 98.01]} rotation={[2.79, 1.07, -2.34]} scale={[1.44, 1.44, 1.44]}>
                    <mesh
                      geometry={nodes.Cilindro_1_138_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_138_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-87.91, 45.28, 11.32]} rotation={[1.52, -0.42, -0.6]} scale={[0.68, 0.68, 0.68]}>
                    <mesh
                      geometry={nodes.Cilindro_139_2_Mat002_0.geometry}
                      material={nodes.Cilindro_139_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[132.84, 25.64, -12.11]} rotation={[0.64, -0.99, -2.58]} scale={[0.84, 0.84, 0.84]}>
                    <mesh
                      geometry={nodes.Cilindro_1_140_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_140_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-45.66, 18.71, -24.85]} rotation={[2.23, -0.61, -1.71]} scale={[0.39, 0.39, 0.39]}>
                    <mesh
                      geometry={nodes.Cilindro_141_2_Mat002_0.geometry}
                      material={nodes.Cilindro_141_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[-61.44, 38.37, 35.49]} rotation={[1.21, -0.06, -1.39]} scale={[0.52, 0.52, 0.52]}>
                    <mesh
                      geometry={nodes.Cilindro_1_142_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_142_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[41.14, 20.74, -32.79]} rotation={[2.37, 0.31, 1.21]} scale={[0.37, 0.37, 0.37]}>
                    <mesh
                      geometry={nodes.Cilindro_143_2_Mat002_0.geometry}
                      material={nodes.Cilindro_143_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[-18.54, 38.95, -66.1]} rotation={[1.82, -0.33, 0.66]} scale={[0.55, 0.55, 0.55]}>
                    <mesh
                      geometry={nodes.Cilindro_1_144_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_144_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[9.48, 26.13, -128.19]} rotation={[0.7, 0.16, -2.75]} scale={[1.2, 1.2, 1.2]}>
                    <mesh
                      geometry={nodes.Cilindro_145_2_Mat002_0.geometry}
                      material={nodes.Cilindro_145_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[73.89, 31.42, 107.77]} rotation={[1.95, -0.26, -1.79]} scale={[1.2, 1.2, 1.2]}>
                    <mesh
                      geometry={nodes.Cilindro_1_146_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_146_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[111.09, 28.25, -61.48]} rotation={[0.66, -0.63, -2.05]} scale={[1.59, 1.59, 1.59]}>
                    <mesh
                      geometry={nodes.Cilindro_147_2_Mat002_0.geometry}
                      material={nodes.Cilindro_147_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[53.51, 45.66, -73.13]} rotation={[1.22, 0.1, -0.08]} scale={[0.66, 0.66, 0.66]}>
                    <mesh
                      geometry={nodes.Cilindro_1_148_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_148_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-33.55, 44.74, -96.27]} rotation={[1.14, 0.5, -0.95]} scale={[0.94, 0.94, 0.94]}>
                    <mesh
                      geometry={nodes.Cilindro_149_2_Mat002_0.geometry}
                      material={nodes.Cilindro_149_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[47.29, 45.6, 80.38]} rotation={[1.65, -0.26, 1.1]} scale={[0.72, 0.72, 0.72]}>
                    <mesh
                      geometry={nodes.Cilindro_1_150_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_150_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[45.24, 29.79, 125.4]} rotation={[2.05, -0.24, -1.83]} scale={[1.33, 1.33, 1.33]}>
                    <mesh
                      geometry={nodes.Cilindro_151_2_Mat002_0.geometry}
                      material={nodes.Cilindro_151_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[-43.15, 38.51, -53.02]} rotation={[1.7, -0.26, -2.1]} scale={[0.53, 0.53, 0.53]}>
                    <mesh
                      geometry={nodes.Cilindro_1_152_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_152_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[93.31, 13.89, -99.79]} rotation={[-0.25, -1.1, -0.93]} scale={[0.64, 0.64, 0.64]}>
                    <mesh
                      geometry={nodes.Cilindro_153_2_Mat002_0.geometry}
                      material={nodes.Cilindro_153_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[-38.69, 45.72, 88.33]} rotation={[1.97, -0.15, 2.82]} scale={[0.79, 0.79, 0.79]}>
                    <mesh
                      geometry={nodes.Cilindro_1_154_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_154_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[16.92, 40.32, -68.95]} rotation={[2.35, 0.47, -2.86]} scale={[0.51, 0.51, 0.51]}>
                    <mesh
                      geometry={nodes.Cilindro_155_2_Mat002_0.geometry}
                      material={nodes.Cilindro_155_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[-105.37, 27.54, 78.27]} rotation={[2.47, 0.42, 0.69]} scale={[1.76, 1.76, 1.76]}>
                    <mesh
                      geometry={nodes.Cilindro_1_156_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_156_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-28.89, 16.26, 45.71]} rotation={[0.07, -0.92, 0.81]} scale={[0.28, 0.28, 0.28]}>
                    <mesh
                      geometry={nodes.Cilindro_157_2_Mat002_0.geometry}
                      material={nodes.Cilindro_157_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[49.78, 43.35, -94.91]} rotation={[1.11, 0.15, -2.11]} scale={[0.81, 0.81, 0.81]}>
                    <mesh
                      geometry={nodes.Cilindro_1_158_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_158_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-43.24, 13.49, -26.42]} rotation={[2.36, -1.23, -0.16]} scale={[0.21, 0.21, 0.21]}>
                    <mesh
                      geometry={nodes.Cilindro_159_2_Mat002_0.geometry}
                      material={nodes.Cilindro_159_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[-77.38, 45.54, 63.38]} rotation={[1.25, -0.07, 0.28]} scale={[0.7, 0.7, 0.7]}>
                    <mesh
                      geometry={nodes.Cilindro_1_160_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_160_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[9.76, 12.04, -49.4]} rotation={[-2.69, 0.28, -1.69]} scale={[0.16, 0.16, 0.16]}>
                    <mesh
                      geometry={nodes.Cilindro_161_2_Mat002_0.geometry}
                      material={nodes.Cilindro_161_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[16.88, 43.11, 110.75]} rotation={[1.84, -0.37, -0.04]} scale={[0.88, 0.88, 0.88]}>
                    <mesh
                      geometry={nodes.Cilindro_1_162_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_162_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[0.87, 21.12, 137.03]} rotation={[2.83, -0.34, 0.82]} scale={[1.39, 1.39, 1.39]}>
                    <mesh
                      geometry={nodes.Cilindro_163_2_Mat002_0.geometry}
                      material={nodes.Cilindro_163_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[133.88, 14.91, -13.79]} rotation={[-1.43, -0.22, -2.5]} scale={[0.39, 0.39, 0.39]}>
                    <mesh
                      geometry={nodes.Cilindro_1_164_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_164_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-68.14, 43.57, -41.3]} rotation={[1.29, -0.16, -0.18]} scale={[0.58, 0.58, 0.58]}>
                    <mesh
                      geometry={nodes.Cilindro_165_2_Mat002_0.geometry}
                      material={nodes.Cilindro_165_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[35.64, 38.52, -58.15]} rotation={[1.97, -0.15, 0.34]} scale={[0.61, 0.61, 0.61]}>
                    <mesh
                      geometry={nodes.Cilindro_1_166_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_166_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[35.59, 38.97, 115.64]} rotation={[1.83, -0.41, -0.27]} scale={[0.97, 0.97, 0.97]}>
                    <mesh
                      geometry={nodes.Cilindro_167_2_Mat002_0.geometry}
                      material={nodes.Cilindro_167_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[-33.62, 20.18, 44.16]} rotation={[0.56, -0.61, 2.03]} scale={[0.38, 0.38, 0.38]}>
                    <mesh
                      geometry={nodes.Cilindro_1_168_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_168_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-48.93, 28.78, 35.62]} rotation={[1.2, -0.6, -2.81]} scale={[0.47, 0.47, 0.47]}>
                    <mesh
                      geometry={nodes.Cilindro_169_2_Mat002_0.geometry}
                      material={nodes.Cilindro_169_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[33.56, 13.87, 41.72]} rotation={[-0.12, 0.36, 2.67]} scale={[0.18, 0.18, 0.18]}>
                    <mesh
                      geometry={nodes.Cilindro_1_170_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_170_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-72.2, 40.02, -5.54]} rotation={[1.63, -0.73, 1.67]} scale={[0.71, 0.71, 0.71]}>
                    <mesh
                      geometry={nodes.Cilindro_171_2_Mat002_0.geometry}
                      material={nodes.Cilindro_171_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[104.36, 42.71, 39.84]} rotation={[1.79, -0.2, -0.83]} scale={[1.08, 1.08, 1.08]}>
                    <mesh
                      geometry={nodes.Cilindro_1_172_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_172_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-112.61, 42.02, 1.77]} rotation={[1.65, 0.63, -1.22]} scale={[0.91, 0.91, 0.91]}>
                    <mesh
                      geometry={nodes.Cilindro_173_2_Mat002_0.geometry}
                      material={nodes.Cilindro_173_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[-49.4, 45.37, 76.3]} rotation={[1.66, -0.17, 2.45]} scale={[0.73, 0.73, 0.73]}>
                    <mesh
                      geometry={nodes.Cilindro_1_174_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_174_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-85.76, 37.86, -81.1]} rotation={[1.33, 0.2, 3.14]} scale={[1.08, 1.08, 1.08]}>
                    <mesh
                      geometry={nodes.Cilindro_175_2_Mat002_0.geometry}
                      material={nodes.Cilindro_175_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[135.97, 8.3, 21.25]} rotation={[-1.27, -0.29, -0.63]} scale={[0.44, 0.44, 0.44]}>
                    <mesh
                      geometry={nodes.Cilindro_1_176_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_176_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-96.18, 43.36, -49.3]} rotation={[1.65, 0.01, 1.62]} scale={[0.82, 0.82, 0.82]}>
                    <mesh
                      geometry={nodes.Cilindro_177_2_Mat002_0.geometry}
                      material={nodes.Cilindro_177_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[-48.04, 19.62, 25.74]} rotation={[0.66, -1.21, 2.38]} scale={[0.39, 0.39, 0.39]}>
                    <mesh
                      geometry={nodes.Cilindro_1_178_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_178_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-78.73, 7.56, 117.58]} rotation={[-3.08, 0.6, -2.3]} scale={[0.93, 0.93, 0.93]}>
                    <mesh
                      geometry={nodes.Cilindro_179_2_Mat002_0.geometry}
                      material={nodes.Cilindro_179_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[45.56, 27.64, 38.67]} rotation={[1.14, 0.98, -1.45]} scale={[0.47, 0.47, 0.47]}>
                    <mesh
                      geometry={nodes.Cilindro_1_180_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_180_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[4.57, 43.4, -77.98]} rotation={[2.05, 0.35, -0.59]} scale={[0.6, 0.6, 0.6]}>
                    <mesh
                      geometry={nodes.Cilindro_181_2_Mat002_0.geometry}
                      material={nodes.Cilindro_181_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[-46.17, 41.95, 105.12]} rotation={[2.26, -0.03, 2.15]} scale={[0.83, 0.83, 0.83]}>
                    <mesh
                      geometry={nodes.Cilindro_1_182_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_182_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-53.1, 45.22, 72.33]} rotation={[1.26, -0.03, -0.04]} scale={[0.85, 0.85, 0.85]}>
                    <mesh
                      geometry={nodes.Cilindro_183_2_Mat002_0.geometry}
                      material={nodes.Cilindro_183_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[-54.09, 25.76, 20.19]} rotation={[0.81, -1.19, 1.38]} scale={[0.43, 0.43, 0.43]}>
                    <mesh
                      geometry={nodes.Cilindro_1_184_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_184_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[76.81, 14.57, 117.52]} rotation={[2.94, -0.52, 1.8]} scale={[0.73, 0.73, 0.73]}>
                    <mesh
                      geometry={nodes.Cilindro_185_2_Mat002_0.geometry}
                      material={nodes.Cilindro_185_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[-34.37, 38.31, 116.71]} rotation={[2.3, 0.24, 1.19]} scale={[1.02, 1.02, 1.02]}>
                    <mesh
                      geometry={nodes.Cilindro_1_186_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_186_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[87.53, 45.22, -48.88]} rotation={[1.05, -0.19, -1.33]} scale={[0.81, 0.81, 0.81]}>
                    <mesh
                      geometry={nodes.Cilindro_187_2_Mat002_0.geometry}
                      material={nodes.Cilindro_187_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[-87.93, 45.61, 27.55]} rotation={[1.74, -0.15, 2.41]} scale={[0.65, 0.65, 0.65]}>
                    <mesh
                      geometry={nodes.Cilindro_1_188_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_188_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[7.37, 28.65, 60.9]} rotation={[0.79, -0.16, 1.32]} scale={[0.42, 0.42, 0.42]}>
                    <mesh
                      geometry={nodes.Cilindro_189_2_Mat002_0.geometry}
                      material={nodes.Cilindro_189_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[-116.32, 11.07, -74.6]} rotation={[-0.16, 1, 0.4]} scale={[0.76, 0.76, 0.76]}>
                    <mesh
                      geometry={nodes.Cilindro_1_190_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_190_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[105.01, 44.06, 21.76]} rotation={[1.86, -0.22, -0.47]} scale={[0.79, 0.79, 0.79]}>
                    <mesh
                      geometry={nodes.Cilindro_191_2_Mat002_0.geometry}
                      material={nodes.Cilindro_191_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[78.89, 21.22, -107.48]} rotation={[0.78, -0.48, -0.13]} scale={1.18}>
                    <mesh
                      geometry={nodes.Cilindro_1_192_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_192_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-121.31, 34.77, -17.92]} rotation={[0.82, 0.89, -1.31]} scale={[1.2, 1.2, 1.2]}>
                    <mesh
                      geometry={nodes.Cilindro_193_2_Mat002_0.geometry}
                      material={nodes.Cilindro_193_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[-40, 25.31, -122.76]} rotation={[0.91, 0.32, 2.85]} scale={[1.24, 1.24, 1.24]}>
                    <mesh
                      geometry={nodes.Cilindro_1_194_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_194_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[-79.37, 27.63, 105.47]} rotation={[2.12, 0.63, -0.41]} scale={[1.67, 1.67, 1.67]}>
                    <mesh
                      geometry={nodes.Cilindro_195_2_Mat002_0.geometry}
                      material={nodes.Cilindro_195_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[-121.18, 20.6, 62.86]} rotation={[2.42, 0.67, 3.14]} scale={[1.25, 1.25, 1.25]}>
                    <mesh
                      geometry={nodes.Cilindro_1_196_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_196_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[50.17, 44.48, -65.27]} rotation={[1.76, 0.2, -1.5]} scale={[0.72, 0.72, 0.72]}>
                    <mesh
                      geometry={nodes.Cilindro_197_2_Mat002_0.geometry}
                      material={nodes.Cilindro_197_2_Mat002_0.material}
                    />
                  </group>
                  <group position={[-81.24, 16.52, 111.39]} rotation={[2.2, 0.6, -1.81]} scale={[1.43, 1.43, 1.43]}>
                    <mesh
                      geometry={nodes.Cilindro_1_198_2_Mat001_0.geometry}
                      material={nodes.Cilindro_1_198_2_Mat001_0.material}
                    />
                  </group>
                  <group position={[67.44, 42.11, -87.7]} rotation={[0.9, -0.04, -1.29]} scale={[0.93, 0.93, 0.93]}>
                    <mesh
                      geometry={nodes.Cilindro_199_2_Mat002_0.geometry}
                      material={nodes.Cilindro_199_2_Mat002_0.material}
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/music.gltf')
