export default [
    {
        id: 1,
        photo: "./images/sample_nft.png",
        profile: "./images/default-prof.png",
        name: "John Darryl",
        title: "NEW WAVE",
        check: true,
        friend: false,
        bid: "0.78",
        bids: "82",
        genre: "classical",
        active: true
    },
    {
        id: 2,
        photo: "./images/sample_nft2.png",
        profile: "./images/default-prof.png", 
        name: "John Darryl",
        title: "Gotta See Part II",
        check: true,
        friend: false,
        bid: "0.78",
        bids: "82",
        genre: "classical",
        active: true
    },
    {
        id: 3,
        photo: "./images/sample_nft3.png",
        profile: "./images/default-prof.png",
        name: "John Darryl",
        title: "Gotta See Part III",
        check: true,
        friend: false,
        bid: "0.78",
        bids: "82",
        genre: "classical",
        active: false
    },
    {
        id: 4,
        photo: "./images/sample_nft3.png",
        profile: "./images/default-prof.png",
        name: "John Darryl",
        title: "Gotta See Part III",
        check: true,
        friend: false,
        bid: "0.78",
        bids: "82",
        genre: "classical",
        active: false
    },
    {
        id: 5,
        photo: "./images/sample_nft3.png",
        profile: "./images/default-prof.png",
        name: "John Darryl",
        title: "Gotta See Part III",
        check: true,
        friend: false,
        bid: "0.78",
        bids: "82",
        genre: "classical",
        active: false
    },
    {
        id: 6,
        photo: "./images/sample_nft3.png",
        profile: "./images/default-prof.png",
        name: "John Darryl",
        title: "Gotta See Part III",
        check: true,
        friend: false,
        bid: "0.78",
        bids: "82",
        genre: "classical",
        active: false
    },

]