export default [
    {
        id: 1,
        photo: "./images/sample_nft.png",
        profile: "./images/default-prof.png",
        name: "John Darryl",
        title: "NEW WAVE",
        check: true,
        friend: false,
        bid: "0.78",
        bids: "82",
        genre: "r&b",
        active: true,
        status: "gold",
        available_nfts: true,
        available_nfts_amt: "69 / 69"
    },
    {
        id: 2,
        photo: "./images/sample_nft2.png",
        profile: "./images/default-prof.png",
        name: "John Darryl",
        title: "NEW WAVE",
        check: true,
        friend: false,
        bid: "0.78",
        bids: "82",
        genre: "hip-hop",
        active: true,
        status: "gold",
        available_nfts: false,
        available_nfts_amt: "69 / 69"
    },
    {
        id: 3,
        photo: "./images/sample_nft3.png",
        profile: "./images/default-prof.png",
        name: "John Darryl",
        title: "NEW WAVE",
        check: true,
        friend: false,
        bid: "0.78",
        bids: "82",
        genre: "rock",
        active: false,
        status: "gold",
        available_nfts: true,
        available_nfts_amt: "69 / 69"
    },
    {
        id: 4,
        photo: "./images/sample_nft3.png",
        profile: "./images/default-prof.png",
        name: "John Darryl",
        title: "NEW WAVE",
        check: true,
        friend: false,
        bid: "0.78",
        bids: "82",
        genre: "pop",
        active: false,
        status: "gold",
        available_nfts: true,
        available_nfts_amt: "69 / 69"
    },
    {
        id: 5,
        photo: "./images/sample_nft.png",
        profile: "./images/default-prof.png",
        name: "John Darryl",
        title: "NEW WAVE",
        check: true,
        friend: false,
        bid: "0.78",
        bids: "82",
        genre: "pop",
        active: true,
        status: "gold",
        available_nfts: true,
        available_nfts_amt: "69 / 69"
    },
    {
        id: 6,
        photo: "./images/sample_nft2.png",
        profile: "./images/default-prof.png",
        name: "John Darryl",
        title: "NEW WAVE",
        check: true,
        friend: false,
        bid: "0.78",
        bids: "82",
        genre: "r&b",
        active: true,
        status: "gold",
        available_nfts: true,
        available_nfts_amt: "69 / 69"
    },

]